language: python
python:
  - "3.4"

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="mysite_MYSQL.settings"
    - PYTHONPATH="/home/travis/build/ChristianGeng/pony-forum"
    - PIP_USE_MIRRORS=true
    
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet

before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres

# command to run tests
script:
  - sh build_app.sh
