# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0003_journals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filename', models.CharField(max_length=400)),
                ('Abstract', models.CharField(max_length=1000)),
                ('Published_At', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Journal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZSIV.Journals')),
            ],
        ),
        migrations.CreateModel(
            name='SykophantJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Journal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZSIV.Journals')),
                ('Sykophant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZSIV.Sykophanten')),
            ],
        ),
    ]
