# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0004_summaries_sykophantjournal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaries',
            old_name='Published_At',
            new_name='Created',
        ),
        migrations.RenameField(
            model_name='summaries',
            old_name='Journal_id',
            new_name='Journal',
        ),
        migrations.AddField(
            model_name='summaries',
            name='Number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summaries',
            name='PublicationDate',
            field=models.DateField(default=datetime.datetime(1901, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='summaries',
            name='SENT',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaries',
            name='Volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summaries',
            name='Year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sykophantjournal',
            unique_together=set([('Sykophant_id', 'Journal_id')]),
        ),
    ]
