# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0005_auto_20160701_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sykophantjournal',
            old_name='Journal_id',
            new_name='Journal',
        ),
        migrations.RenameField(
            model_name='sykophantjournal',
            old_name='Sykophant_id',
            new_name='Sykophant',
        ),
        migrations.AlterUniqueTogether(
            name='sykophantjournal',
            unique_together=set([('Sykophant', 'Journal')]),
        ),
    ]
