# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 12:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0007_auto_20160702_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sykophanten',
            new_name='Mitarbeiter',
        ),
        migrations.AlterField(
            model_name='summaries',
            name='Created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 2, 12, 35, 2, 822570, tzinfo=utc)),
        ),
    ]
