# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0008_auto_20160702_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SykophantJournal',
            new_name='MAJournal',
        ),
        migrations.RenameField(
            model_name='majournal',
            old_name='Sykophant',
            new_name='MA',
        ),
        migrations.AlterField(
            model_name='summaries',
            name='Created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 2, 12, 39, 44, 600528, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='majournal',
            unique_together=set([('MA', 'Journal')]),
        ),
    ]
