# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0009_auto_20160702_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaries',
            name='Created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 2, 12, 40, 29, 611113, tzinfo=utc)),
        ),
    ]
