# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0010_auto_20160702_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='journals',
            name='Subscriptions',
            field=models.ManyToManyField(through='ZSIV.MAJournal', to='ZSIV.Mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='summaries',
            name='Created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 4, 20, 0, 35, 420126, tzinfo=utc)),
        ),
    ]
