# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0016_auto_20160710_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaries',
            name='Created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 10, 16, 37, 8, 962909, tzinfo=utc)),
        ),
    ]
