# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0018_auto_20160710_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='Subscriptions',
            field=models.ManyToManyField(through='ZSIV.MAJournal', to='ZSIV.Journals'),
        ),
        migrations.AlterField(
            model_name='summaries',
            name='Created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 10, 17, 23, 14, 278582, tzinfo=utc)),
        ),
    ]
