# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0019_auto_20160710_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaries',
            old_name='Number',
            new_name='Heftnummer',
        ),
        migrations.RenameField(
            model_name='summaries',
            old_name='Volume',
            new_name='Jahrgang',
        ),
        migrations.RemoveField(
            model_name='summaries',
            name='Abstract',
        ),
        migrations.RemoveField(
            model_name='summaries',
            name='Created',
        ),
        migrations.RemoveField(
            model_name='summaries',
            name='PublicationDate',
        ),
        migrations.RemoveField(
            model_name='summaries',
            name='Year',
        ),
        migrations.AddField(
            model_name='journals',
            name='Kurztitel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='summaries',
            name='CreationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 11, 12, 40, 6, 66722, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='summaries',
            name='SENT',
            field=models.BooleanField(default=False),
        ),
    ]
