# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0021_auto_20160711_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaries',
            name='CreationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='summaries',
            name='Jahrgang',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], null=True),
        ),
    ]
