# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0022_auto_20160711_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaries',
            name='IV',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
