# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 15:55
from __future__ import unicode_literals

import ZSIV.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0024_auto_20160711_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaries',
            name='IV',
            field=models.FileField(default=False, upload_to=ZSIV.models.upload_location),
        ),
    ]
