# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0026_auto_20160711_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaries',
            name='Inhaltsverzeichnis',
            field=models.FileField(default=False, upload_to='/media/win-d/myfiles/2016/django/media_cdn'),
        ),
    ]
