# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZSIV', '0028_auto_20160720_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summaries',
            unique_together=set([('Journal', 'Heftnummer', 'Jahrgang')]),
        ),
    ]
